In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
df.shape

(891, 12)

In [ ]:
df = 

In [7]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

In [11]:
df.dtypes

col1    int64
col2    int64
dtype: object

In [9]:
df = df[d, (columns = "a", "b")]

SyntaxError: invalid syntax (<ipython-input-9-bf0a4ea8407b>, line 1)

In [12]:
df = pd.DataFrame(data=d, dtype=np.int8)
df.dtypes

col1    int8
col2    int8
dtype: object

In [13]:
s = pd.Series({'a': 1, 'b': 2, 'c': 3})
s.ndim

1

In [18]:
df1 = pd.DataFrame([{'a': 1, 'b': 2, 'c': 3}])
df1

a  b  c
0  1  2  3

In [19]:
df1.dtypes

a    int64
b    int64
c    int64
dtype: object

In [20]:
df1.head()

a  b  c
0  1  2  3

In [4]:
a = [1,2,3,"Ali", "Veli",'Ahmet']

In [5]:
a

[1, 2, 3, 'Ali', 'Veli', 'Ahmet']

In [2]:
import pandas as pd
import numpy as np


In [6]:
pd.DataFrame(a, columns = ["Isimler"])

Isimler
0       1
1       2
2       3
3     Ali
4    Veli
5   Ahmet

In [26]:
a

[1, 2, 3, 'Ali', 'Veli', 'Ahmet']

In [29]:
df.dtypes

col1    int8
col2    int8
dtype: object

In [7]:
import numpy as np
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
df = pd.DataFrame(m, columns = ["var1", "var2","var3"])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [9]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [39]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [40]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['var1', 'var2', 'var3'], dtype='object')]

In [41]:
df.ndim

2

In [42]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [11]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [12]:
sozluk

{'var1': array([6, 7, 2, 1, 0]),
 'var2': array([7, 4, 1, 0, 4]),
 'var3': array([3, 8, 8, 4, 2])}

In [14]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     6     7     3
1     7     4     8
2     2     1     8
3     1     0     4
4     0     4     2

In [15]:
df.index = ["a","b",'c','d','e']
df

var1  var2  var3
a     6     7     3
b     7     4     8
c     2     1     8
d     1     0     4
e     0     4     2

In [50]:
df.values

array([[9, 6, 7],
       [9, 6, 1],
       [1, 7, 7],
       [3, 5, 7],
       [1, 3, 3]])

In [56]:
df.drop("a", axis = 0)

var1  var2  var3
b     9     6     1
c     1     7     7
d     3     5     7
e     1     3     3

In [57]:
df["var1"]

a    9
b    9
c    1
d    3
e    1
Name: var1, dtype: int32

In [18]:
df.drop("c")
df

var1  var2  var3
a     6     7     3
b     7     4     8
c     2     1     8
d     1     0     4
e     0     4     2

In [22]:
df.iloc[0:3]

var1  var2  var3
a     6     7     3
b     7     4     8
c     2     1     8

In [23]:
df.drop("var3", axis = 1, inplace = True)

In [24]:
df

var1  var2
a     6     7
b     7     4
c     2     1
d     1     0
e     0     4

In [27]:
df["var3"] = df['var1'] / df["var2"] 

In [28]:
df

var1  var2      var3
a     6     7  0.857143
b     7     4  1.750000
c     2     1  2.000000
d     1     0       inf
e     0     4  0.000000

In [30]:
df.drop("var3", axis = 1, inplace = True)

In [31]:
df.values

array([[6, 7],
       [7, 4],
       [2, 1],
       [1, 0],
       [0, 4]])

In [32]:
df.iloc[0:3,0:2]

var1  var2
a     6     7
b     7     4
c     2     1

In [35]:
df.iloc[0:3]["var2"]

a    7
b    4
c    1
Name: var2, dtype: int32

In [41]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,4))
df = pd.DataFrame(m, columns = ["var1","var2","var3","var4"])

In [42]:
df

var1  var2  var3  var4
0    23     6     4    10
1    20    22     5    15
2    20    22     9     9
3    19     5     6    11
4    17    29     3     3
5    23    28     6    13
6    29    28    29    28
7     9     6     6     6
8     1    25    20    26
9    19    14    11    15

In [45]:
df.values

array([[23,  6,  4, 10],
       [20, 22,  5, 15],
       [20, 22,  9,  9],
       [19,  5,  6, 11],
       [17, 29,  3,  3],
       [23, 28,  6, 13],
       [29, 28, 29, 28],
       [ 9,  6,  6,  6],
       [ 1, 25, 20, 26],
       [19, 14, 11, 15]])

In [46]:
df.var1 > 9

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
8    False
9     True
Name: var1, dtype: bool

In [49]:
df[df.var1 > 9]

var1  var2  var3  var4
0    23     6     4    10
1    20    22     5    15
2    20    22     9     9
3    19     5     6    11
4    17    29     3     3
5    23    28     6    13
6    29    28    29    28
9    19    14    11    15

In [50]:
df[(df.var1 < 18) & (df.var2 > 20)]

var1  var2  var3  var4
4    17    29     3     3
8     1    25    20    26

In [53]:
df.loc[(df.var1 < 20),["var2","var4"]]

var2  var4
3     5    11
4    29     3
7     6     6
8    25    26
9    14    15

In [63]:
import numpy as np
import pandas as pd
m = np.random.randint(0,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df1

var1  var2  var3
0    24    29    17
1    16     6    12
2     1    26    19
3     8    11     9
4     0     0     7

In [64]:
df2 = df1 + 99

In [65]:
df2

var1  var2  var3
0   123   128   116
1   115   105   111
2   100   125   118
3   107   110   108
4    99    99   106

In [68]:
pd.concat([df1, df2], axis = 0)

var1  var2  var3
0    24    29    17
1    16     6    12
2     1    26    19
3     8    11     9
4     0     0     7
0   123   128   116
1   115   105   111
2   100   125   118
3   107   110   108
4    99    99   106

In [70]:
pd.concat([df1, df2], ignore_index = True)

var1  var2  var3
0    24    29    17
1    16     6    12
2     1    26    19
3     8    11     9
4     0     0     7
5   123   128   116
6   115   105   111
7   100   125   118
8   107   110   108
9    99    99   106

In [74]:
import numpy as np
import pandas as pd
df1 = pd.DataFrame({"Calisanlar": ["Ali","Ahmet","Ayse","Mehmet"], 
                    "Departman": ["IK", "Personel", "Pazarlama", "Satis"]})
df2 = pd.DataFrame({"Calisanlar": ["Ali","Ahmet","Ayse","Mehmet"], 
                    "Giris_tarihi": [2009, 2010, 2006, 2012]})

In [75]:
df2

Calisanlar  Giris_tarihi
0        Ali          2009
1      Ahmet          2010
2       Ayse          2006
3     Mehmet          2012

In [76]:
df = pd.concat([df1, df2], ignore_index = True)

In [77]:
df

Calisanlar  Departman  Giris_tarihi
0        Ali         IK           NaN
1      Ahmet   Personel           NaN
2       Ayse  Pazarlama           NaN
3     Mehmet      Satis           NaN
4        Ali        NaN        2009.0
5      Ahmet        NaN        2010.0
6       Ayse        NaN        2006.0
7     Mehmet        NaN        2012.0

In [78]:
pd.merge(df1, df2, on = "Calisanlar")

Calisanlar  Departman  Giris_tarihi
0        Ali         IK          2009
1      Ahmet   Personel          2010
2       Ayse  Pazarlama          2006
3     Mehmet      Satis          2012

In [79]:
df = pd.read_csv("train.csv")

In [83]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [85]:
df.mean()


PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [88]:
df.median()

PassengerId    446.0000
Survived         0.0000
Pclass           3.0000
Age             28.0000
SibSp            0.0000
Parch            0.0000
Fare            14.4542
dtype: float64

In [89]:
df["Age"].mean()

29.69911764705882

In [92]:
df.describe().T

count        mean         std   min       25%       50%    75%  \
PassengerId  891.0  446.000000  257.353842  1.00  223.5000  446.0000  668.5   
Survived     891.0    0.383838    0.486592  0.00    0.0000    0.0000    1.0   
Pclass       891.0    2.308642    0.836071  1.00    2.0000    3.0000    3.0   
Age          714.0   29.699118   14.526497  0.42   20.1250   28.0000   38.0   
SibSp        891.0    0.523008    1.102743  0.00    0.0000    0.0000    1.0   
Parch        891.0    0.381594    0.806057  0.00    0.0000    0.0000    0.0   
Fare         891.0   32.204208   49.693429  0.00    7.9104   14.4542   31.0   

                  max  
PassengerId  891.0000  
Survived       1.0000  
Pclass         3.0000  
Age           80.0000  
SibSp          8.0000  
Parch          6.0000  
Fare         512.3292

In [94]:
df.shape

(891, 12)

In [96]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [98]:
df.dropna().describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [104]:
df.groupby("Sex")

In [106]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [107]:
df.groupby(["Sex","Embarked","Pclass"]).agg({"Age": "mean", "Survived":"mean"})

Age  Survived
Sex    Embarked Pclass                     
female C        1       36.052632  0.976744
                2       19.142857  1.000000
                3       14.062500  0.652174
       Q        1       33.000000  1.000000
                2       30.000000  1.000000
                3       22.850000  0.727273
       S        1       32.704545  0.958333
                2       29.719697  0.910448
                3       23.223684  0.375000
male   C        1       40.111111  0.404762
                2       25.937500  0.200000
                3       25.016800  0.232558
       Q        1       44.000000  0.000000
                2       57.000000  0.000000
                3       28.142857  0.076923
       S        1       41.897188  0.354430
                2       30.875889  0.154639
                3       26.574766  0.128302

In [109]:
df.groupby("Sex").agg({"Age": ["min", "max", np.median], "Survived":"mean"}).T

Sex                 female       male
Age      min      0.750000   0.420000
         max     63.000000  80.000000
         median  27.000000  29.000000
Survived mean     0.742038   0.188908

In [113]:
df = pd.read_csv("retail_dataset.csv")
df.head()

0       1     2       3       4       5       6
0   Bread    Wine  Eggs    Meat  Cheese  Pencil  Diaper
1   Bread  Cheese  Meat  Diaper    Wine    Milk  Pencil
2  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
3  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
4    Meat  Pencil  Wine     NaN     NaN     NaN     NaN

In [125]:
df.describe().T

count unique     top freq
0   315      9   Bread   74
1   285      9    Meat   47
2   245      9    Eggs   52
3   187      9    Milk   45
4   133      9    Wine   36
5    71      9  Pencil   13
6    41      9   Bread   11

In [130]:
df[["0","2"]].head()

0     2
0   Bread  Eggs
1   Bread  Meat
2  Cheese  Eggs
3  Cheese  Eggs
4    Meat  Wine

In [131]:
df = pd.read_csv("train.csv")

In [132]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [135]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [138]:
df[["Age", "Parch"]].apply(np.sum, axis = 0)

Age      21205.17
Parch      340.00
dtype: float64

In [140]:
import pandas as pd
df = pd.DataFrame({"Gruplar": ["A", 'B', 'C', 'A', 'B', 'C'], "Degisken1":[10,20,30,40,50,60],
                   "Degiken2": [111,222,333,444,555,666]}, columns = ["Gruplar","Degisken1","Degiken2"])

In [141]:
df

Gruplar  Degisken1  Degiken2
0       A         10       111
1       B         20       222
2       C         30       333
3       A         40       444
4       B         50       555
5       C         60       666